kind: pipeline
name: default

steps:
  - name: build
    image: node:12.6
    commands:
      - npm install
      - npm run build
      - mkdir /drone/src/topublish
      - mv ./build/* /drone/src/topublish
  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: topublish/
      temporary_base: tmp/
      target_branch: gh-pages

